In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [139]:
veriler = pd.read_csv("veriler.csv")
veriler

ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [140]:
ulke = veriler.iloc[:,0:1].values
ulke

array([['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['tr'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['us'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr'],
       ['fr']], dtype=object)

In [141]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
ulke[:,0] = le.fit_transform(veriler.iloc[:,0])
#burada processing yaptım yani sınıflandırma yaptım.
ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
ulke

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [142]:
c = veriler.iloc[:,-1:].values
c
le = preprocessing.LabelEncoder()
c[:,-1] = le.fit_transform(veriler.iloc[:,-1])
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()
c

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [143]:
veriler1 = veriler.iloc[:,1:4]
veriler1

boy  kilo  yas
0   130    30   10
1   125    36   11
2   135    34   10
3   133    30    9
4   129    38   12
5   180    90   30
6   190    80   25
7   175    90   35
8   177    60   22
9   185   105   33
10  165    55   27
11  155    50   44
12  160    58   39
13  162    59   41
14  167    62   55
15  174    70   47
16  193    90   23
17  187    80   27
18  183    88   28
19  159    40   29
20  164    66   32
21  166    56   42

In [144]:
ulke = pd.DataFrame(data=ulke, index = range(22), columns=["tr","fr","us"])

In [145]:
c = pd.DataFrame(data = c[:,:1], index = range(22), columns=["cinsiyet"])
c

cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0

In [146]:
s1 = pd.concat([ulke,veriler1],axis = 1)
s1

tr   fr   us  boy  kilo  yas
0   0.0  1.0  0.0  130    30   10
1   0.0  1.0  0.0  125    36   11
2   0.0  1.0  0.0  135    34   10
3   0.0  1.0  0.0  133    30    9
4   0.0  1.0  0.0  129    38   12
5   0.0  1.0  0.0  180    90   30
6   0.0  1.0  0.0  190    80   25
7   0.0  1.0  0.0  175    90   35
8   0.0  1.0  0.0  177    60   22
9   0.0  0.0  1.0  185   105   33
10  0.0  0.0  1.0  165    55   27
11  0.0  0.0  1.0  155    50   44
12  0.0  0.0  1.0  160    58   39
13  0.0  0.0  1.0  162    59   41
14  0.0  0.0  1.0  167    62   55
15  1.0  0.0  0.0  174    70   47
16  1.0  0.0  0.0  193    90   23
17  1.0  0.0  0.0  187    80   27
18  1.0  0.0  0.0  183    88   28
19  1.0  0.0  0.0  159    40   29
20  1.0  0.0  0.0  164    66   32
21  1.0  0.0  0.0  166    56   42

In [147]:
c

cinsiyet
0        1.0
1        1.0
2        0.0
3        0.0
4        1.0
5        1.0
6        1.0
7        1.0
8        0.0
9        1.0
10       0.0
11       0.0
12       0.0
13       0.0
14       0.0
15       1.0
16       1.0
17       1.0
18       1.0
19       0.0
20       0.0
21       0.0

In [148]:
datam = pd.concat([s1,c], axis = 1)
datam

tr   fr   us  boy  kilo  yas  cinsiyet
0   0.0  1.0  0.0  130    30   10       1.0
1   0.0  1.0  0.0  125    36   11       1.0
2   0.0  1.0  0.0  135    34   10       0.0
3   0.0  1.0  0.0  133    30    9       0.0
4   0.0  1.0  0.0  129    38   12       1.0
5   0.0  1.0  0.0  180    90   30       1.0
6   0.0  1.0  0.0  190    80   25       1.0
7   0.0  1.0  0.0  175    90   35       1.0
8   0.0  1.0  0.0  177    60   22       0.0
9   0.0  0.0  1.0  185   105   33       1.0
10  0.0  0.0  1.0  165    55   27       0.0
11  0.0  0.0  1.0  155    50   44       0.0
12  0.0  0.0  1.0  160    58   39       0.0
13  0.0  0.0  1.0  162    59   41       0.0
14  0.0  0.0  1.0  167    62   55       0.0
15  1.0  0.0  0.0  174    70   47       1.0
16  1.0  0.0  0.0  193    90   23       1.0
17  1.0  0.0  0.0  187    80   27       1.0
18  1.0  0.0  0.0  183    88   28       1.0
19  1.0  0.0  0.0  159    40   29       0.0
20  1.0  0.0  0.0  164    66   32       0.0
21  1.0  0.0  0.0  166    56   42       0.0

In [149]:
from sklearn.model_selection import train_test_split

In [150]:
x_train, x_test, y_train, y_test =  train_test_split(s1,c,test_size = 0.33, random_state = 0)

In [151]:
x_train

tr   fr   us  boy  kilo  yas
8   0.0  1.0  0.0  177    60   22
6   0.0  1.0  0.0  190    80   25
16  1.0  0.0  0.0  193    90   23
4   0.0  1.0  0.0  129    38   12
2   0.0  1.0  0.0  135    34   10
5   0.0  1.0  0.0  180    90   30
17  1.0  0.0  0.0  187    80   27
9   0.0  0.0  1.0  185   105   33
7   0.0  1.0  0.0  175    90   35
18  1.0  0.0  0.0  183    88   28
3   0.0  1.0  0.0  133    30    9
0   0.0  1.0  0.0  130    30   10
15  1.0  0.0  0.0  174    70   47
12  0.0  0.0  1.0  160    58   39

In [156]:
from sklearn.linear_model import LinearRegression

In [157]:
regressor = LinearRegression()

In [159]:
regressor.fit(x_train,y_train)

LinearRegression()

In [160]:
y_pred = regressor.predict(x_test)
y_pred

array([[ 0.98720204],
       [-0.12036863],
       [ 0.05009703],
       [ 0.07137418],
       [ 0.72473935],
       [ 0.64615044],
       [-0.03567453],
       [ 0.32612171]])

In [162]:
boy = s1.iloc[:,3:4]
boy

boy
0   130
1   125
2   135
3   133
4   129
5   180
6   190
7   175
8   177
9   185
10  165
11  155
12  160
13  162
14  167
15  174
16  193
17  187
18  183
19  159
20  164
21  166

In [163]:
sol = datam.iloc[:,:3]
sol

tr   fr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0

In [165]:
sag = datam.iloc[:,4:]
sag

kilo  yas  cinsiyet
0     30   10       1.0
1     36   11       1.0
2     34   10       0.0
3     30    9       0.0
4     38   12       1.0
5     90   30       1.0
6     80   25       1.0
7     90   35       1.0
8     60   22       0.0
9    105   33       1.0
10    55   27       0.0
11    50   44       0.0
12    58   39       0.0
13    59   41       0.0
14    62   55       0.0
15    70   47       1.0
16    90   23       1.0
17    80   27       1.0
18    88   28       1.0
19    40   29       0.0
20    66   32       0.0
21    56   42       0.0

In [166]:
veri = pd.concat([sol,sag],axis=1)
veri

tr   fr   us  kilo  yas  cinsiyet
0   0.0  1.0  0.0    30   10       1.0
1   0.0  1.0  0.0    36   11       1.0
2   0.0  1.0  0.0    34   10       0.0
3   0.0  1.0  0.0    30    9       0.0
4   0.0  1.0  0.0    38   12       1.0
5   0.0  1.0  0.0    90   30       1.0
6   0.0  1.0  0.0    80   25       1.0
7   0.0  1.0  0.0    90   35       1.0
8   0.0  1.0  0.0    60   22       0.0
9   0.0  0.0  1.0   105   33       1.0
10  0.0  0.0  1.0    55   27       0.0
11  0.0  0.0  1.0    50   44       0.0
12  0.0  0.0  1.0    58   39       0.0
13  0.0  0.0  1.0    59   41       0.0
14  0.0  0.0  1.0    62   55       0.0
15  1.0  0.0  0.0    70   47       1.0
16  1.0  0.0  0.0    90   23       1.0
17  1.0  0.0  0.0    80   27       1.0
18  1.0  0.0  0.0    88   28       1.0
19  1.0  0.0  0.0    40   29       0.0
20  1.0  0.0  0.0    66   32       0.0
21  1.0  0.0  0.0    56   42       0.0

In [167]:
x_train,x_test,y_train,y_test = train_test_split(veri,boy,test_size=0.33,random_state=0)

In [168]:
x_train

tr   fr   us  kilo  yas  cinsiyet
8   0.0  1.0  0.0    60   22       0.0
6   0.0  1.0  0.0    80   25       1.0
16  1.0  0.0  0.0    90   23       1.0
4   0.0  1.0  0.0    38   12       1.0
2   0.0  1.0  0.0    34   10       0.0
5   0.0  1.0  0.0    90   30       1.0
17  1.0  0.0  0.0    80   27       1.0
9   0.0  0.0  1.0   105   33       1.0
7   0.0  1.0  0.0    90   35       1.0
18  1.0  0.0  0.0    88   28       1.0
3   0.0  1.0  0.0    30    9       0.0
0   0.0  1.0  0.0    30   10       1.0
15  1.0  0.0  0.0    70   47       1.0
12  0.0  0.0  1.0    58   39       0.0

In [169]:
x_test

tr   fr   us  kilo  yas  cinsiyet
20  1.0  0.0  0.0    66   32       0.0
10  0.0  0.0  1.0    55   27       0.0
14  0.0  0.0  1.0    62   55       0.0
13  0.0  0.0  1.0    59   41       0.0
1   0.0  1.0  0.0    36   11       1.0
21  1.0  0.0  0.0    56   42       0.0
11  0.0  0.0  1.0    50   44       0.0
19  1.0  0.0  0.0    40   29       0.0

In [170]:
y_train

boy
8   177
6   190
16  193
4   129
2   135
5   180
17  187
9   185
7   175
18  183
3   133
0   130
15  174
12  160

In [171]:
r2 = LinearRegression()

In [172]:
r2.fit(x_train,y_train)

LinearRegression()

In [173]:
y_pred = r2.predict(x_test)
y_pred

array([[182.26638686],
       [152.87161474],
       [162.79386375],
       [158.30668577],
       [130.82888952],
       [173.96138408],
       [150.12782663],
       [157.26898922]])

In [174]:
y_test

boy
20  164
10  165
14  167
13  162
1   125
21  166
11  155
19  159

In [176]:
import statsmodels.api as sm

In [178]:
#burada değişkenlerden hangisi p value değerini daha çok etkiliyorsa onu çıkartıcaz bunun için bu işlemleri yapıyoruz bu backward elminationdır

In [183]:
X = np.append(arr = np.ones((22,1)).astype(int), values = veri, axis = 1)
#en başa birlerden oluşan bir kolon ekledi.
X

array([[  1.,   0.,   1.,   0.,  30.,  10.,   1.],
       [  1.,   0.,   1.,   0.,  36.,  11.,   1.],
       [  1.,   0.,   1.,   0.,  34.,  10.,   0.],
       [  1.,   0.,   1.,   0.,  30.,   9.,   0.],
       [  1.,   0.,   1.,   0.,  38.,  12.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  30.,   1.],
       [  1.,   0.,   1.,   0.,  80.,  25.,   1.],
       [  1.,   0.,   1.,   0.,  90.,  35.,   1.],
       [  1.,   0.,   1.,   0.,  60.,  22.,   0.],
       [  1.,   0.,   0.,   1., 105.,  33.,   1.],
       [  1.,   0.,   0.,   1.,  55.,  27.,   0.],
       [  1.,   0.,   0.,   1.,  50.,  44.,   0.],
       [  1.,   0.,   0.,   1.,  58.,  39.,   0.],
       [  1.,   0.,   0.,   1.,  59.,  41.,   0.],
       [  1.,   0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   1.,   0.,   0.,

In [185]:
X_l = veri.iloc[:,[0,1,2,3,4,5]].values
X_l

array([[  0.,   1.,   0.,  30.,  10.,   1.],
       [  0.,   1.,   0.,  36.,  11.,   1.],
       [  0.,   1.,   0.,  34.,  10.,   0.],
       [  0.,   1.,   0.,  30.,   9.,   0.],
       [  0.,   1.,   0.,  38.,  12.,   1.],
       [  0.,   1.,   0.,  90.,  30.,   1.],
       [  0.,   1.,   0.,  80.,  25.,   1.],
       [  0.,   1.,   0.,  90.,  35.,   1.],
       [  0.,   1.,   0.,  60.,  22.,   0.],
       [  0.,   0.,   1., 105.,  33.,   1.],
       [  0.,   0.,   1.,  55.,  27.,   0.],
       [  0.,   0.,   1.,  50.,  44.,   0.],
       [  0.,   0.,   1.,  58.,  39.,   0.],
       [  0.,   0.,   1.,  59.,  41.,   0.],
       [  0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   0.,   0.,  40.,  29.,   0.],
       [  1.,   0.,   0.,  66.,  32.,   0.],
       [  1.,   0.,   0.,  56.,  42.,   0.]])

In [186]:
X_l = np.array(X_l,dtype=float)
X_l

array([[  0.,   1.,   0.,  30.,  10.,   1.],
       [  0.,   1.,   0.,  36.,  11.,   1.],
       [  0.,   1.,   0.,  34.,  10.,   0.],
       [  0.,   1.,   0.,  30.,   9.,   0.],
       [  0.,   1.,   0.,  38.,  12.,   1.],
       [  0.,   1.,   0.,  90.,  30.,   1.],
       [  0.,   1.,   0.,  80.,  25.,   1.],
       [  0.,   1.,   0.,  90.,  35.,   1.],
       [  0.,   1.,   0.,  60.,  22.,   0.],
       [  0.,   0.,   1., 105.,  33.,   1.],
       [  0.,   0.,   1.,  55.,  27.,   0.],
       [  0.,   0.,   1.,  50.,  44.,   0.],
       [  0.,   0.,   1.,  58.,  39.,   0.],
       [  0.,   0.,   1.,  59.,  41.,   0.],
       [  0.,   0.,   1.,  62.,  55.,   0.],
       [  1.,   0.,   0.,  70.,  47.,   1.],
       [  1.,   0.,   0.,  90.,  23.,   1.],
       [  1.,   0.,   0.,  80.,  27.,   1.],
       [  1.,   0.,   0.,  88.,  28.,   1.],
       [  1.,   0.,   0.,  40.,  29.,   0.],
       [  1.,   0.,   0.,  66.,  32.,   0.],
       [  1.,   0.,   0.,  56.,  42.,   0.]])

In [187]:
#OLS istatistiksel değerleri çıkarmaya yarar
model = sm.OLS(boy,X_l).fit()
# boy ile bağımsız değişken olan data arasında ilişki kuruyoruz

In [190]:
model.summary()
#bütün amaç OlS regression sonuçlarını elde etmek için bu raporu almak çok önemli bizim için şuan önemli olan p değerleri
#burada amacımız backward algoritması adımları gereği en yüksek p değerini elemek

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.849
Method:                 Least Squares   F-statistic:                     24.69
Date:                Sun, 11 Sep 2022   Prob (F-statistic):           5.41e-07
Time:                        22:18:30   Log-Likelihood:                -73.950
No. Observations:                  22   AIC:                             159.9
Df Residuals:                      16   BIC:                             166.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           114.0688      8.145     14.005      0.000      96.802     131.335
x2           108.3030      5.736     18.880      0.000      96.143     120.463
x3           104.4714      9.195     11.361      0.000      84.978     123.964
x4             0.9211      0.119      7.737      0.000       0.669       1.174
x5             0.0814      0.221      0.369      0.717      -0.386       0.549
x6           -10.5980      5.052     -2.098      0.052     -21.308       0.112
==============================================================================
Omnibus:                        1.031   Durbin-Watson:                   2.759
Prob(Omnibus):                  0.597   Jarque-Bera (JB):                0.624
Skew:                           0.407   Prob(JB):                        0.732
Kurtosis:                       2.863   Cond. No.                         524.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [191]:
# şuan 4 index teki elemanı çıkartıp yeniden hesaplama yapıyoruz
X_l = veri.iloc[:,[0,1,2,3,5]].values
X_l = np.array(X_l,dtype = float)
model = sm.OLS(boy,X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.884
Model:                            OLS   Adj. R-squared:                  0.857
Method:                 Least Squares   F-statistic:                     32.47
Date:                Sun, 11 Sep 2022   Prob (F-statistic):           9.32e-08
Time:                        22:22:07   Log-Likelihood:                -74.043
No. Observations:                  22   AIC:                             158.1
Df Residuals:                      17   BIC:                             163.5
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           115.6583      6.734     17.175      0.000     101.451     129.866
x2           109.0786      5.200     20.978      0.000      98.108     120.049
x3           106.5445      7.090     15.026      0.000      91.585     121.504
x4             0.9405      0.104      9.029      0.000       0.721       1.160
x5           -11.1093      4.733     -2.347      0.031     -21.096      -1.123
==============================================================================
Omnibus:                        0.871   Durbin-Watson:                   2.719
Prob(Omnibus):                  0.647   Jarque-Bera (JB):                0.459
Skew:                           0.351   Prob(JB):                        0.795
Kurtosis:                       2.910   Cond. No.                         397.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [193]:
#daha iyi bir sonuç için aynı işlemi tekrarlıyoruz
X_l = veri.iloc[:,[0,1,2,3]].values
X_l = np.array(X_l,dtype = float)
model = sm.OLS(boy,X_l).fit()
model.summary()
#statsmodel ile modelin istatistiksel değerlerine ulaştık

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    boy   R-squared:                       0.847
Model:                            OLS   Adj. R-squared:                  0.821
Method:                 Least Squares   F-statistic:                     33.16
Date:                Sun, 11 Sep 2022   Prob (F-statistic):           1.52e-07
Time:                        22:23:33   Log-Likelihood:                -77.131
No. Observations:                  22   AIC:                             162.3
Df Residuals:                      18   BIC:                             166.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           119.8136      7.265     16.491      0.000     104.550     135.077
x2           109.8084      5.804     18.919      0.000      97.615     122.002
x3           114.4212      6.984     16.382      0.000      99.747     129.095
x4             0.7904      0.092      8.595      0.000       0.597       0.984
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.855
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                1.499
Skew:                           0.605   Prob(JB):                        0.473
Kurtosis:                       3.416   Cond. No.                         369.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""