In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
veriler = pd.read_csv('odev_tenis.csv')

In [5]:
veriler.head()

outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

In [6]:
# outlook kısmını sayısal değere dönüştürmemiz gerekiyor
# onehot encoding yapacağız

In [7]:
# windy,play kısmınıda sayısal değere dönüştürmemiz gerekiyor
# label encoding yapacağız bu kısımda da

In [8]:
play=veriler.iloc[:,-1:].values
play

array([['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['yes'],
       ['no']], dtype=object)

In [9]:
windy=veriler.iloc[:,-2:-1].values
windy

array([[False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True]])

In [10]:
from sklearn.preprocessing import LabelEncoder
le2=LabelEncoder()
windy[:,0]=le2.fit_transform(windy[:,0])
windy

array([[False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True]])

In [11]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [12]:
play[:,0]=le.fit_transform(play[:,0])

In [13]:
play

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder
veriler2 = veriler.apply(LabelEncoder().fit_transform)
# burada bütün kolonlar üzerine labelencoding işlemini uyguladık

In [15]:
veriler2

outlook  temperature  humidity  windy  play
0         2           11         4      0     0
1         2            8         6      1     0
2         0           10         5      0     1
3         1            4         9      0     1
4         1            2         3      0     1
5         1            1         1      1     0
6         0            0         0      1     1
7         2            6         8      0     0
8         2            3         1      0     1
9         1            7         3      0     1
10        2            7         1      1     1
11        0            6         6      1     1
12        0            9         2      0     1
13        1            5         7      1     0

In [16]:
c=veriler2.iloc[:,:1]

In [17]:
c

outlook
0         2
1         2
2         0
3         1
4         1
5         1
6         0
7         2
8         2
9         1
10        2
11        0
12        0
13        1

In [19]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
c=ohe.fit_transform(c).toarray()
print(c)


[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [20]:
havadurumu = pd.DataFrame(data = c, index = range(14), columns=['o','r','s'])
sonveriler = pd.concat([havadurumu,veriler.iloc[:,1:3]],axis = 1)
sonveriler = pd.concat([veriler2.iloc[:,-2:],sonveriler], axis = 1)

In [21]:
sonveriler

windy  play    o    r    s  temperature  humidity
0       0     0  0.0  0.0  1.0           85        85
1       1     0  0.0  0.0  1.0           80        90
2       0     1  1.0  0.0  0.0           83        86
3       0     1  0.0  1.0  0.0           70        96
4       0     1  0.0  1.0  0.0           68        80
5       1     0  0.0  1.0  0.0           65        70
6       1     1  1.0  0.0  0.0           64        65
7       0     0  0.0  0.0  1.0           72        95
8       0     1  0.0  0.0  1.0           69        70
9       0     1  0.0  1.0  0.0           75        80
10      1     1  0.0  0.0  1.0           75        70
11      1     1  1.0  0.0  0.0           72        90
12      0     1  1.0  0.0  0.0           81        75
13      1     0  0.0  1.0  0.0           71        91

In [23]:
from sklearn.model_selection import train_test_split
# huminity değerini tahmin işlemi yapacağız
x_train, x_test,y_train,y_test = train_test_split(sonveriler.iloc[:,:-1],sonveriler.iloc[:,-1:],test_size=0.33, random_state=0)

In [24]:
x_train

windy  play    o    r    s  temperature
13      1     0  0.0  1.0  0.0           71
9       0     1  0.0  1.0  0.0           75
1       1     0  0.0  0.0  1.0           80
7       0     0  0.0  0.0  1.0           72
10      1     1  0.0  0.0  1.0           75
3       0     1  0.0  1.0  0.0           70
0       0     0  0.0  0.0  1.0           85
5       1     0  0.0  1.0  0.0           65
12      0     1  1.0  0.0  0.0           81

In [25]:
y_train

humidity
13        91
9         80
1         90
7         95
10        70
3         96
0         85
5         70
12        75

In [26]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)

print(y_pred)

[[84.45365573]
 [63.93839954]
 [85.76050662]
 [64.21013241]
 [75.06793322]]


In [27]:
# backward elemination

In [28]:
# backward elemination ile gereksiz değişkenleri çıkartıcağız

In [32]:
import statsmodels.api as sm
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1 )
X_l = sonveriler.iloc[:,[0,1,2,3,4,5]].values


In [33]:
r_ols = sm.OLS(endog = sonveriler.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Thu, 17 Nov 2022   Prob (F-statistic):              0.661
Time:                        00:21:23   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.5

/Users/mehmetakifkiraz/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [34]:
sonveriler=sonveriler.iloc[:,1:]

In [35]:
sonveriler

play    o    r    s  temperature  humidity
0      0  0.0  0.0  1.0           85        85
1      0  0.0  0.0  1.0           80        90
2      1  1.0  0.0  0.0           83        86
3      1  0.0  1.0  0.0           70        96
4      1  0.0  1.0  0.0           68        80
5      0  0.0  1.0  0.0           65        70
6      1  1.0  0.0  0.0           64        65
7      0  0.0  0.0  1.0           72        95
8      1  0.0  0.0  1.0           69        70
9      1  0.0  1.0  0.0           75        80
10     1  0.0  0.0  1.0           75        70
11     1  1.0  0.0  0.0           72        90
12     1  1.0  0.0  0.0           81        75
13     0  0.0  1.0  0.0           71        91

In [38]:
import statsmodels.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=sonveriler.iloc[:,:-1], axis=1 )
X_l = sonveriler.iloc[:,[0,1,2,3,4]].values
r_ols = sm.OLS(endog = sonveriler.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Thu, 17 Nov 2022   Prob (F-statistic):              0.546
Time:                        00:25:19   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.3

/Users/mehmetakifkiraz/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [39]:
x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]

In [40]:
regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)

In [41]:
y_pred

array([[77.98135142],
       [68.29304916],
       [81.05037539],
       [71.44926132],
       [75.78905304]])

In [42]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86